export const styles = {
  task: {
    color: "gray.600",
    fontSize: "sm",
    p: 2,
    bg: "orange.100",
    borderRadius: "5px 0 0 5px",
    display: "flex",
    alignItems: "center",
    borderLeft: "6px solid #FBD38D",
    minHeight: "2rem",
    minW: 0,
    overflowX: "hidden",
    position: "relative",
  },
  executionTime: {
    color: "gray.600",
    bg: "yellow.200",
    boxShadow: "sm",
    rounded: "sm",
    alignItems: "center",
    gap: 1,
    px: 2,
    position: "absolute",
    right: 2,
  },
};
